### ISSUE TITLE
make的问题

### ISSUE THREAD

**Issue by AHEADer** [nju-ics/ics2015#14]
gcc 6.1 在3.6的时候(实现加载程序的loader)，make kernel会报错，会编译kernel/src/fs/fs.c，报错信息如下：
error: ‘file_table’ defined but not used [-Werror=unused-const-variable=]
 static const file_info file_table[] = {
cc1: all warnings being treated as errors
make: **\* [kernel/Makefile.part:3: obj/kernel/fs/fs.o] Error 1

但是在gcc 4.9.2的情况下不会报错

**Comment by Wangyao14cyy** [comment]
hust unique，zhangjunda？

2016-07-01 8:45 GMT+08:00 Zhang Junda notifications@github.com:

**Comment by AHEADer** [comment]
是我，gcc4.9.3编译没有问题，后续的有问题，Makefile的话没看到是哪里把kernel底下的模块编译了，gcc5.3和6.1都不行

**Comment by ghost** [comment]
已修復 , 請執行git pull後嘗試重新編譯.
