### ISSUE TITLE
Why use `instr_fetch` but not `swaddr_read` directly?

### ISSUE THREAD

**Issue by swordfeng** [nju-ics/ics2015#2]
Is there any essential difference? Or `instr_fetch` must be modified sooner or later?

**Comment by ghost** [comment]
Using `instr_fetch` can tell us whether a memory accessing is related to instruction or data. This makes the code more readable. Besides, this can make it easy to implement Icache and Dcache in the future. Just a design consideration.

**Comment by swordfeng** [comment]
That's reasonable. But I think we cannot really speed up our Nemu CPU by simulating cache in memory...

**Comment by ghost** [comment]
Yes, you are right. Simulating cache will hurt the performance. But NEMU is designed for teaching. Students learn how cache works in class. Implementing a cache by simulation and put it into a system(NEMU) will give them better understanding. Facing the trade off between teaching and performance, we prefer the former.
