### ISSUE TITLE
neg指令需要更新cf标志

### ISSUE THREAD

**Issue by zhangboyang** [nju-ics/ics2015#3]
neg指令需要更新cf标志，如果不更新，在对long long型整数进行取负时会发生错误，因为gcc会将取负编译成neg指令后紧接着一条adc指令。

**Comment by ghost** [comment]
請問你是在哪個測試文件編譯出neg和adc指令的?

**Comment by zhangboyang** [comment]
是我自己添加的测试样例

[LLneg.txt](https://github.com/nju-ics/ics2015/files/37668/LLneg.txt)
[LLneg.c.txt](https://github.com/nju-ics/ics2015/files/37669/LLneg.c.txt)

**Comment by ghost** [comment]
那你就自己加上更新cf的代碼吧, 當時只考慮了testcase裏面的文件. 設計裏面還有很多簡化, 有可能跑一個新的測試用例就不行了.

**Comment by zhangboyang** [comment]
好吧～
